-- AlterEnum
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'REJECTED_PRICE_CHANGE';

-- AlterTable
ALTER TABLE "orders"
ADD COLUMN "statusReason" TEXT,
ADD COLUMN "priceLockedAt" TIMESTAMP,
ADD COLUMN "expiresAt" TIMESTAMP;

